apiVersion: "v1"
kind: "Service"
metadata:
  name: "mattdekok-service"
  namespace: "default"
  labels:
    app: "mattdekok.dev"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "mattdekok.dev"
  type: "LoadBalancer"
  loadBalancerIP: ""