---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: stg
  namespace: "default"
  labels:
    app: "mattdekok.dev"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "mattdekok.dev"
  template:
    metadata:
      labels:
        app: "mattdekok.dev"
    spec:
      containers:
      - name: "mattdekok-dev-sha256-1"
        image: gcr.io/PROJECT_ID/IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30 