apiVersion: v1
kind: Service
metadata:
  name: nuxt-frontend
  namespace: default
  labels:
    app: nuxt-frontend
    tier: frontend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: nuxt-frontend
  type: LoadBalancer